[daa-displays] src/daa-displays/daa-player.ts:2464:30 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(timeoutId: string | number | Timeout): void', gave the following error.
   Argument of type 'Timer' is not assignable to parameter of type 'string | number | Timeout'.
     Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
  Overload 2 of 2, '(id: number): void', gave the following error.
   Argument of type 'Timer' is not assignable to parameter of type 'number'.
2464                 clearTimeout(this.timers[tk[i]]);
                                 ~~~~~~~~~~~~~~~~~~